import tseslint from 'typescript-eslint'
import stylistic from '@stylistic/eslint-plugin'

/** @type {import('eslint').Linter.Config[]} */
export default [
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  stylistic.configs['recommended-flat'],
  {
    files: [
      '**/*.ts',
    ],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: [
      '**/*.{ts,tsx,vue}',
    ],
    rules: {
      'id-length': ['error', { min: 2 }],
      'no-duplicate-imports': ['warn'],
      'no-extra-parens': ['off'],
      '@typescript-eslint/array-type': ['warn'],
      '@typescript-eslint/consistent-type-definitions': ['off'],
      '@typescript-eslint/explicit-function-return-type': ['warn', { allowExpressions: true }],
      '@typescript-eslint/explicit-member-accessibility': ['warn'],
      '@typescript-eslint/method-signature-style': ['warn', 'property'],
      '@typescript-eslint/no-confusing-void-expression': ['off'],
      '@typescript-eslint/no-empty-function': ['off'],
      '@typescript-eslint/no-empty-object-type': ['off'],
      '@typescript-eslint/no-explicit-any': ['off'],
      '@typescript-eslint/no-floating-promises': ['off'],
      '@typescript-eslint/no-inferrable-types': ['off'],
      '@typescript-eslint/no-unsafe-argument': ['off'],
      '@typescript-eslint/no-unsafe-assignment': ['off'],
      '@typescript-eslint/no-unsafe-call': ['off'],
      '@typescript-eslint/no-unsafe-member-access': ['off'],
      '@typescript-eslint/no-unsafe-return': ['off'],
      '@typescript-eslint/no-unused-vars': ['warn', { ignoreRestSiblings: true }],
      '@typescript-eslint/non-nullable-type-assertion-style': ['warn'],
      '@typescript-eslint/parameter-properties': ['warn'],
      '@typescript-eslint/prefer-enum-initializers': ['warn'],
      '@typescript-eslint/prefer-nullish-coalescing': ['warn', { ignoreConditionalTests: true }],
      '@typescript-eslint/prefer-readonly': ['warn'],
      '@typescript-eslint/require-array-sort-compare': ['warn'],
      '@typescript-eslint/require-await': ['off'],
      '@typescript-eslint/restrict-template-expressions': ['off'],
      '@typescript-eslint/switch-exhaustiveness-check': ['warn'],
      '@typescript-eslint/unbound-method': ['off'],
      '@typescript-eslint/unified-signatures': ['off'],
      '@stylistic/arrow-parens': ['warn', 'always'],
      '@stylistic/array-bracket-newline': ['warn', 'consistent'],
      '@stylistic/array-element-newline': ['warn', { consistent: true, multiline: true }],
      '@stylistic/brace-style': ['warn', '1tbs'],
      '@stylistic/comma-dangle': ['warn', { arrays: 'always-multiline', objects: 'always-multiline', imports: 'never', exports: 'never', functions: 'always-multiline' }],
      '@stylistic/comma-spacing': ['warn'],
      '@stylistic/curly-newline': ['warn', { multiline: true, consistent: true }],
      '@stylistic/dot-location': ['warn', 'property'],
      '@stylistic/func-call-spacing': ['warn'],
      '@stylistic/function-call-spacing': ['warn'],
      '@stylistic/implicit-arrow-linebreak': ['warn'],
      '@stylistic/key-spacing': ['warn', { afterColon: true }],
      '@stylistic/keyword-spacing': ['warn', { before: true, after: true }],
      '@stylistic/member-delimiter-style': ['warn', { multiline: { delimiter: 'comma', requireLast: true }, singleline: { delimiter: 'comma', requireLast: false } }],
      '@stylistic/newline-per-chained-call': ['warn', { ignoreChainWithDepth: 2 }],
      '@stylistic/no-confusing-arrow': ['warn'],
      '@stylistic/object-curly-newline': ['warn', { multiline: true, consistent: true }],
      '@stylistic/object-curly-spacing': ['warn', 'always'],
      '@stylistic/multiline-ternary': ['off'],
      '@stylistic/operator-linebreak': ['warn', 'none', { overrides: { '?': 'before', ':': 'before', '||': 'before', '&&': 'before' } }],
      '@stylistic/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
      '@stylistic/one-var-declaration-per-line': ['warn'],
      '@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
      '@stylistic/space-before-function-paren': ['warn', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
      '@stylistic/spaced-comment': ['warn', 'always', { markers: ['/'] }],
      '@stylistic/switch-colon-spacing': ['warn'],
    },
  },
  {
    files: ['**/*.js'],
    ...tseslint.configs.disableTypeChecked,
  },
]
