import pluginVue from 'eslint-plugin-vue'
import rootConfig from '../eslint.config.js'

/** @type {import('eslint').Linter.Config[]} */
export default [
  ...rootConfig,
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['**/*.{ts,vue}'],
    languageOptions: {
      parserOptions: {
        parser: '@typescript-eslint/parser',
        extraFileExtensions: ['.vue'],
        projectService: false,
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ['**/*.vue'],
    rules: {
      '@stylistic/indent': ['off'],
      'vue/script-indent': ['warn', 2, { baseIndent: 1, switchCase: 1 }],
      'vue/array-bracket-newline': ['warn', 'consistent'],
      'vue/array-element-newline': ['warn', { consistent: true, multiline: true }],
      'vue/brace-style': ['warn', '1tbs'],
      'vue/block-tag-newline': ['warn'],
      'vue/camelcase': ['warn'],
      'vue/comma-dangle': ['warn', { arrays: 'always-multiline', objects: 'always-multiline', imports: 'never', exports: 'never', functions: 'never' }],
      'vue/comma-spacing': ['warn'],
      'vue/component-definition-name-casing': ['warn'],
      'vue/component-name-in-template-casing': ['off'],
      'vue/component-options-name-casing': ['warn'],
      'vue/component-tags-order': ['error', { order: ['script', 'template', 'style'] }],
      'vue/custom-event-name-casing': ['warn'],
      'vue/dot-location': ['warn', 'property'],
      'vue/dot-notation': ['warn'],
      'vue/first-attribute-linebreak': ['warn'],
      'vue/func-call-spacing': ['warn'],
      'vue/html-button-has-type': ['warn'],
      'vue/html-closing-bracket-newline': ['warn'],
      'vue/html-closing-bracket-spacing': ['warn'],
      'vue/html-comment-content-newline': ['warn'],
      'vue/html-comment-content-spacing': ['warn'],
      'vue/html-comment-indent': ['warn'],
      'vue/html-end-tags': ['warn'],
      'vue/html-indent': ['warn'],
      'vue/html-quotes': ['warn'],
      'vue/html-self-closing': ['warn'],
      'vue/key-spacing': ['warn', { afterColon: true }],
      'vue/keyword-spacing': ['warn', { before: true, after: true }],
      'vue/match-component-file-name': ['warn'],
      'vue/max-attributes-per-line': ['warn', { singleline: { max: 5 }, multiline: { max: 1 } }],
      'vue/multi-word-component-names': ['warn'],
      'vue/multiline-html-element-content-newline': ['warn'],
      'vue/mustache-interpolation-spacing': ['warn'],
      'vue/new-line-between-multi-line-property': ['warn'],
      'vue/next-tick-style': ['warn'],
      'vue/no-boolean-default': ['warn'],
      'vue/no-child-content': ['warn'],
      'vue/no-duplicate-attr-inheritance': ['warn'],
      'vue/no-empty-component-block': ['warn'],
      'vue/no-expose-after-await': ['warn'],
      'vue/no-extra-parens': ['warn'],
      'vue/no-invalid-model-keys': ['warn'],
      'vue/no-lone-template': ['warn'],
      'vue/no-multi-spaces': ['warn'],
      'vue/no-multiple-objects-in-class': ['warn'],
      'vue/no-multiple-slot-args': ['warn'],
      'vue/no-potential-component-option-typo': ['warn'],
      'vue/no-reserved-component-names': ['warn'],
      'vue/no-spaces-around-equal-signs-in-attribute': ['warn'],
      'vue/no-static-inline-styles': ['warn'],
      'vue/no-template-shadow': ['warn'],
      'vue/no-this-in-before-route-enter': ['warn'],
      'vue/no-undef-properties': ['warn'],
      'vue/no-unused-properties': ['warn'],
      'vue/no-unused-refs': ['warn'],
      'vue/no-use-computed-property-like-method': ['warn'],
      'vue/no-useless-concat': ['warn'],
      'vue/no-useless-mustaches': ['warn'],
      'vue/no-useless-v-bind': ['warn'],
      'vue/no-v-html': ['warn'],
      'vue/no-v-text': ['warn'],
      'vue/object-curly-newline': ['warn', { multiline: true, consistent: true }],
      'vue/object-curly-spacing': ['warn', 'always'],
      'vue/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
      'vue/one-component-per-file': ['warn'],
      'vue/operator-linebreak': ['warn', 'none'],
      'vue/order-in-components': ['warn'],
      'vue/padding-line-between-blocks': ['warn'],
      'vue/prefer-separate-static-class': ['warn'],
      'vue/prefer-template': ['warn'],
      'vue/prop-name-casing': ['warn'],
      'vue/require-default-prop': ['warn'],
      'vue/require-direct-export': ['warn'],
      'vue/require-explicit-emits': ['warn'],
      'vue/require-expose': ['warn'],
      'vue/require-name-property': ['warn'],
      'vue/require-prop-types': ['warn'],
      'vue/singleline-html-element-content-newline': ['warn'],
      'vue/space-in-parens': ['warn'],
      'vue/this-in-template': ['warn'],
      'vue/v-bind-style': ['warn'],
      'vue/v-on-event-hyphenation': ['warn'],
      'vue/v-on-function-call': ['warn'],
      'vue/v-on-style': ['warn'],
      'vue/v-slot-style': ['warn'],
    },
  },
]
